"""Models 'Admin' and 'Operator' are optimized and upgraded by method 'relationship()'. Also added field 'phone_number' for model 'User'

Revision ID: 2a7039b13601
Revises: 93b5dc965692
Create Date: 2025-12-11 22:00:46.417941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7039b13601'
down_revision: Union[str, Sequence[str], None] = '93b5dc965692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'full_name')
    op.drop_column('admins', 'username')
    op.drop_column('operators', 'username')
    op.drop_column('operators', 'telegram_full_name')
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.add_column('operators', sa.Column('telegram_full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('operators', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('admins', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('admins', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
